### ISSUE TITLE
npm install (dev) failed on edge-js postinstall

### ISSUE THREAD

**Issue by zypA13510** [dtjohnson/xlsx-populate#207]
See: agracio/electron-edge-js#16
Looks like a lot of dependencies are outdated. Someone should update them I guess?

Environment: Ubuntu 18.04.1 LTS
Log:
```console
$ npm install
> edge-cs@1.2.1 install /home/user/Documents/GitHub/xlsx-populate/node_modules/edge-cs
> node tools/install.js


> uws@9.14.0 install /home/user/Documents/GitHub/xlsx-populate/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> edge-js@10.1.0 install /home/user/Documents/GitHub/xlsx-populate/node_modules/edge-js
> node tools/install.js

make: Entering directory '/home/user/Documents/GitHub/xlsx-populate/node_modules/edge-js/build'
  TOUCH Release/obj.target/edge_nativeclr.stamp
  CXX(target) Release/obj.target/edge_coreclr/src/common/v8synchronizationcontext.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/callbackhelper.o
  CXX(target) Release/obj.target/edge_coreclr/src/common/edge.o
  CXX(target) Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o
In file included from ../src/CoreCLREmbedding/json/casablanca/include/cpprest/json.h:37:0,
                 from ../src/CoreCLREmbedding/coreclrembedding.cpp:8:
../src/CoreCLREmbedding/json/casablanca/include/cpprest/asyncrt_utils.h:44:10: fatal error: xlocale.h: No such file or directory
 #include <xlocale.h>
          ^~~~~~~~~~~
compilation terminated.
edge_coreclr.target.mk:127: recipe for target 'Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o' failed
make: *** [Release/obj.target/edge_coreclr/src/CoreCLREmbedding/coreclrembedding.o] Error 1
make: Leaving directory '/home/user/Documents/GitHub/xlsx-populate/node_modules/edge-js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/user/Documents/GitHub/xlsx-populate/node_modules/edge-js
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/watchify/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by LesterLyu** [comment]
This project uses edge-js to run c# code, i.e. `e2e-generate`. 
Since `e2e-generate` requires `Microsoft.Office.Interop.Excel`, which only exists on Windows platform. Then it is OK that edge-js cannot properly install on ububtu.

**Comment by zypA13510** [comment]
Ok, guess I need to read the doc more carefully.
Still, if we can upgrade `edge-js` to a newer version, it would at least prevent the error during `npm install`.

**Comment by dtjohnson** [comment]
Deps are updated.
