### ISSUE TITLE
No way to clear hyperlinks

### ISSUE THREAD

**Issue by MatthewPinheiro** [dtjohnson/xlsx-populate#216]
calling `cell.hyperlink(undefined)` results in an the following error:
```
Error: Cell.hyperlink: Invalid arguments.
    at ArgHandler.handle (path\to\file\node_modules\xlsx-populate\lib\ArgHandler.js:50:15)
    at Cell.hyperlink (path\to\file\node_modules\xlsx-populate\lib\Cell.js:191:14)
```
As far as I know this means that there's no way to clear a hyperlink from a cell. Any suggestions?

**Comment by alandoyle95** [comment]
try doing `cell.hyperlink(null)`
