### ISSUE TITLE
Error: _RichText.value: Invalid arguments.

### ISSUE THREAD

**Issue by TranBaVinhSon** [dtjohnson/xlsx-populate#230]
Thanks for the greate package 
I have an error when reading excel file, And when I tried with another file such as `const filePath = "../static/excel/demo.xlsx"`, I didn't get any errors, is that `xlsx-populate` issue or my excel file's issue ?

```javascript
function insertData(dataObject) {
  const filePath = "../static/excel/demo.xlsx"
  XlsxPopulate.fromFileAsync(filePath)
    .then(workbook => {
      // handle logic here
      return workbook.toFileAsync(filePath);
    })
    .catch(error => {
      console.log('Error', error)
    })
}
```

Error:

```
Error Error: _RichText.value: Invalid arguments.
    at ArgHandler.handle (xxx/node_modules/xlsx-populate/lib/ArgHandler.js:50:15)
    at RichTextFragment.value (xxx/node_modules/xlsx-populate/lib/RichTextFragment.js:76:14)
    at new RichTextFragment (xxx/node_modules/xlsx-populate/lib/RichTextFragment.js:42:18)
    at new RichText (xxx/node_modules/xlsx-populate/lib/RichText.js:23:33)
    at Cell._parseNode (xxx/node_modules/xlsx-populate/lib/Cell.js:596:35)
    at Cell._init (xxx/node_modules/xlsx-populate/lib/Cell.js:541:18)
    at new Cell (xxx/node_modules/xlsx-populate/lib/Cell.js:24:14)
    at _node.children.forEach.cellNode (xxx/node_modules/xlsx-populate/lib/Row.js:352:26)
    at Array.forEach (<anonymous>)
    at Row._init (xxx/node_modules/xlsx-populate/lib/Row.js:351:29)
```

**Comment by happy-tanuki** [comment]
I also got this error from ver 1.20.0.

The `RichTextFragment`'s constructor accepts `value` {string|Object}, but `this.value(value)` accepts only `string`. So an object excepting `r` occurs the error.
https://github.com/dtjohnson/xlsx-populate/blob/master/lib/RichTextFragment.js#L42

If I tried to add an condition (`typeof value === 'string'`),
then the error is gone, but some node is drop out.
(for example, rPh or phoneticPr)

[demo.xlsx](https://github.com/dtjohnson/xlsx-populate/files/3449877/demo.xlsx)
[demo2.xlsx](https://github.com/dtjohnson/xlsx-populate/files/3449878/demo2.xlsx)

**Comment by LesterLyu** [comment]
I will take a look tomorrow.

**Comment by TranBaVinhSon** [comment]
@LesterLyu Yeah sir, please take a look, I'm `xlsx-poplute` for my project and it works with some files and failed at some files. Kind of weird

**Comment by LesterLyu** [comment]
Keep in mind this library won't generate phonetics for Kanji. Thus, whenever you modified a cell that contains phonetic nodes, they phonetic nodes will be removed.

**Comment by TranBaVinhSon** [comment]
I just tested with new code and it worked very well. Thanks for your work!
